kind: KafkaRestClass
apiVersion: platform.confluent.io/v1beta1
metadata:
  name: default
  namespace: confluent
spec:
  kafkaRest:
    #endpoint: http://host.docker.internal:8090
    endpoint: http://kafka-3:8090
    authentication:
      type: basic
      basic:
        secretRef: simple-example-auth-credential
