apiVersion: v1
kind: Secret
metadata:
  name: simple-example-auth-credential
  namespace: confluent
type: Opaque
stringData:
  basic.txt: |
    username: admin
    password: admin-secret
  bearer.txt: |
    username: admin
    password: admin-secret
