apiVersion: v1
kind: Secret
metadata:
  name: simple-example-auth-credential
  namespace: confluent
type: kubernetes.io/basic-auth
stringData:
  basic.txt: |
    username=admin
    password=admin-secret
