apiVersion: platform.confluent.io/v1beta1
kind: Schema
metadata:
  name: payment-schema
  namespace: confluent
spec:
  compatibilityLevel: BACKWARD
  data:
    configRef: payment-schema-config
    format: avro
  mode: READWRITE
  name: payments-value
  normalize: true
  schemaRegistryRest:
    endpoint: http://schema-registry:8081
    authentication:
      type: basic
      basic:
        secretRef: simple-example-auth-credential
