apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: payments
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 4
  configs:
    message.timestamp.type: "LogAppendTime"
  kafkaRestClassRef:
    name: default
