apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: demo-topic-1
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 4
  configs:
    message.timestamp.type: "LogAppendTime"
  kafkaRest:
    endpoint: http://kafka-3:8090
